version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: souk-postgres
    command: postgres -c log_statement='all'
    restart: always
    ports:
      - "55432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      options:
        max-size: 50m
